version: '3'
services:   
    nginx:
        image: nginx:latest
        container_name: nginx
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        ports:
            - "8080:80"
        #depends_on ensures the nginx doesn't close because the
        #flask isn't finished running - "race condition".
        depends_on:
            - flask 
        networks:
            - nginxnet
    
    
    flask:
        build: .
        container_name: flask
        volumes:
            - ./:/opt/services/flask/src
        networks:
            - nginxnet
            - dbnet
        
        #depends_on ensures the flask app doesn't close because the
        #database isn't finished running - "race condition".
        depends_on:
            - database
            
    database: 
        restart: always
        image: postgres:latest
        container_name: database
        volumes:
            - dbdata:/var/lib/postgresql/data
        networks:
            - dbnet
            - nginxnet

#name database to preserve it between down and up   
#without name it will close between uses.         
volumes:
    dbdata:

      
networks:
  dbnet:
    driver: bridge
  nginxnet:
    driver: bridge